@echo off

REM Get script directory
set SCRIPT_DIR=%~dp0
set SCRIPT_DIR=%SCRIPT_DIR:~0,-1%

set WASM32_UNKNOWN_UNKNOWN_STDLIB=%SCRIPT_DIR%
set CARGO_TARGET_WASM32_UNKNOWN_UNKNOWN_RUSTFLAGS=-L %WASM32_UNKNOWN_UNKNOWN_STDLIB%\lib\ -lstatic=c -lstatic=c++abi
set CARGO_TARGET_WASM32_UNKNOWN_UNKNOWN_RUSTFLAGS=%CARGO_TARGET_WASM32_UNKNOWN_UNKNOWN_RUSTFLAGS% --Z wasm_c_abi=spec
set CXXFLAGS_wasm32_unknown_unknown=-isystem %WASM32_UNKNOWN_UNKNOWN_STDLIB%\include-libc\
set CXXFLAGS_wasm32_unknown_unknown=%CXXFLAGS_wasm32_unknown_unknown% -D_BYTE_ORDER=_LITTLE_ENDIAN -D__MATH_GENERIC=1 -nostdlib -D_LIBCPP_HAS_NO_LOCALIZATION
set CXXFLAGS_wasm32_unknown_unknown=%CXXFLAGS_wasm32_unknown_unknown% -isystem %WASM32_UNKNOWN_UNKNOWN_STDLIB%\include\
set CXXFLAGS_wasm32_unknown_unknown=%CXXFLAGS_wasm32_unknown_unknown% -DHAVE___CXA_THREAD_ATEXIT_IMPL -DLIBCXXABI_BAREMETAL -DLIBCXXABI_NON_DEMANGLING_TERMINATE -DLIBCXXABI_SILENT_TERMINATE -D_LIBCPP_DISABLE_EXTERN_TEMPLATE -D_LIBCPP_HAS_NO_LIBRARY_ALIGNED_ALLOCATION -D_LIBCXXABI_HAS_NO_THREADS -D_BYTE_ORDER=_LITTLE_ENDIAN -D__OpenBSD__ -DRUST_CXX_NO_EXCEPTIONS -DENOLINK
set CXXFLAGS_wasm32_unknown_unknown=%CXXFLAGS_wasm32_unknown_unknown% -fexceptions -D__WASM32_UNKNOWN_UNKNOWN__
set CFLAGS_wasm32_unknown_unknown=%CXXFLAGS_wasm32_unknown_unknown%
set CXXFLAGS_wasm32_unknown_unknown=%CXXFLAGS_wasm32_unknown_unknown% -isystem %WASM32_UNKNOWN_UNKNOWN_STDLIB%\include\c++\v1\
set BINDGEN_EXTRA_CLANG_ARGS_wasm32_unknown_unknown=-fvisibility=default